version: 0.2

env:
    variables:
        NODE_TAG_NAME: "16.15.1-alpine"
        DOCKER_REPOSITORY_NAME: "055264279425.dkr.ecr.us-east-1.amazonaws.com"

phases:
  install:

    commands:
      # Update system packages
      - echo Updating and Installing system dependencies...
#      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      # tempo fix "|| true"
      - apt-get update -y -q --list-cleanup || true

  build:
    commands:
      # Builds an Angular application:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${DOCKER_REPOSITORY_NAME}
      - docker pull node:${NODE_TAG_NAME}
      - docker tag node:${NODE_TAG_NAME} 055264279425.dkr.ecr.us-east-1.amazonaws.com/base-images:node-${NODE_TAG_NAME}
      - docker push 055264279425.dkr.ecr.us-east-1.amazonaws.com/base-images:node-${NODE_TAG_NAME}
      - echo Build is successfully completed on `date`
