version: 0.2

phases:
  install:

    commands:
      # Update system packages
      - echo Updating and Installing system dependencies...
#      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      # tempo fix "|| true"
      - apt-get update -y -q --list-cleanup || true

      # Install all necessary dependencies:
      - echo Installing source NPM dependencies...
      - npm install

  build:
    commands:
      # Builds an Angular application:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 055264279425.dkr.ecr.us-east-1.amazonaws.com
      - docker build -t newflix:latest -t newflix:${CODEBUILD_BUILD_NUMBER} -f docker-files/Dockerfile .
      - echo Build is successfully completed on `date`
      - docker tag newflix:${CODEBUILD_BUILD_NUMBER} 055264279425.dkr.ecr.us-east-1.amazonaws.com/newflix:${CODEBUILD_BUILD_NUMBER}
      - docker tag newflix:latest 055264279425.dkr.ecr.us-east-1.amazonaws.com/newflix:latest
      - docker push 055264279425.dkr.ecr.us-east-1.amazonaws.com/newflix --all-tags
      -

  post_build:
    commands:
#      - echo Application deployment is started on `date`
#      - printf '{"Image":"%s"}' "055264279425.dkr.ecr.us-east-1.amazonaws.com/newflix:${CODEBUILD_BUILD_NUMBER}" > "image-def.json"
      - bash ./scripts/generateDockerRun.sh 055264279425.dkr.ecr.us-east-1.amazonaws.com/newflix:${CODEBUILD_BUILD_NUMBER}
artifacts:
    files:
        - Dockerrun.aws.json
