version: 0.2
# Buildspec for BOSS, zip and upload to S3 server and client artifacts
env:
  variables:
    SOURCE_OUTPUT_BUCKET: "newflix-nx-artifacts"
    SOURCE_PATH: "source"
    TARGET_BRANCH: "master"

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      # Update system packages
      - apt-get update -y -q
      # Install dependencies
#      - npm install -g @nrwl/cli@13.10.2
      - npm install --no-progress
      - SOURCE_BRANCH=$(echo $CODEBUILD_WEBHOOK_TRIGGER | awk '{split($0, a,"/"); print a[2]}')
      # Detect affected libs
      - nx affected:packages --base=${TARGET_BRANCH}~1 --head=${TARGET_BRANCH}
      # Detect affected apps
      - AFFECTED_APPS=$(nx affected:apps --base=${TARGET_BRANCH}~1 --head=${TARGET_BRANCH} | tail -n +3 | awk '{print $NF}')
      - echo ${AFFECTED_APPS}
      # Clean-up workspace
      - rm -rf ./node_modules ./dist
      # Archive workspace
      - zip -qr source.zip .
      # Upload workspace archive(s) to S3
      - for APP in $(echo ${AFFECTED_APPS}); do aws s3 cp source.zip s3://${SOURCE_OUTPUT_BUCKET}/${SOURCE_PATH}/${APP}/${APP}.zip --metadata CommitID="${CODEBUILD_RESOLVED_SOURCE_VERSION}",BranchName="${CODEBUILD_SOURCE_VERSION}",RepoURL="${CODEBUILD_SOURCE_REPO_URL}"; done
